### ISSUE TITLE
MAX7219 display output mirrored

### ISSUE THREAD

**Issue by tommayor30** [jegade/esp8266-insta-counter#7]
Hi,
A great code that works really well. The output on my MAX7219 display is mirrored. 
I usually fix this by changing the MAX72xx hardware to ‘ICSTATION_HW’. 

I can’t find where to do this within your code. 
Is it possible to specify different types of MAX7219 displays?

Your help is appreciated. 

Thanks.

**Comment by jegade** [comment]
hi, 
sorry, the counter use the u8g2 lib, which have no further options to configure the display. The fastest solution, was to buy the matching display. You can also try to change the display here https://github.com/jegade/esp8266-insta-counter/blob/5a71eb4c35de33a7c992d481c17d4342768d9b5a/followercounter/followercounter.ino#L36 to other layouts https://github.com/olikraus/u8g2/wiki/u8g2reference#carduino-example

Maybe you can add a photo to the issue to unterstand the kind of mirror.

Jens

**Comment by tommayor30** [comment]
Thank you for getting back to me so quickly. 
I have attached a photo. It is where each panel needs mirroring individually. But you may be right that I need to find a compatitble display, as changing the types didn’t work for this display (eg. U8G2_R1, _MIRROR etc.)

I tried changing these around but with no luck. 
![9830B3B6-412D-47C3-8506-43275D43B483](https://user-images.githubusercontent.com/66795679/84433511-4be11b80-ac26-11ea-909d-35f5c8745253.jpeg)

**Comment by jegade** [comment]
Ok, please let me know if you find a working one. I have buyed my at amazon:
https://www.amazon.de/AZDelivery-MAX7219-Matrix-Anzeigemodul-Arduino/dp/B079HVW652

**Comment by tommayor30** [comment]
Just wanted to let you know that my new screen came and it works perfectly. Thanks for the cool code and support! Keep up the good work!
![5B16B201-E72B-4F85-8182-20C5135D178F](https://user-images.githubusercontent.com/66795679/84569924-f02ba500-ad81-11ea-8e11-566f41622aa0.jpeg)

**Comment by jegade** [comment]
Ty, what's your insta name? Are you following me?

**Comment by tommayor30** [comment]
what is your instagram and we will give you a follow!

**Comment by jegade** [comment]
jens_digital_woodwork - there are also post about the case design  :+1:

**Comment by tommayor30** [comment]
I was just researching / designing my own wooden case so will have a look! thank you
