### ISSUE TITLE
Im Schematic werden die 3V3 mit dem Display verbunden anstatt die 5V

### ISSUE THREAD

**Issue by Gonzo578** [jegade/esp8266-insta-counter#9]
Die Bilder an sich sind i.O. und alles funktioniert :-). Nur im Schaltplan schein ein Dreher drin zu sein.

**Comment by matti04** [comment]
@Gonzo578 Danke, habe das aus Versehen vertauscht

**Comment by jegade** [comment]
Danke euch, wir hatten das später geändert. Grundsätzlich lief das Display auch mit 3.3, aber 5v sind hier besser.
